# Generated by Django 3.2.8 on 2021-10-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_naiss', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
