# Generated by Django 3.2.8 on 2021-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiEmployees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_naiss',
            field=models.DateField(),
        ),
    ]
